// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ContentService.Infrastructure.Persistence.Sql.Queries.QueryModels;

public partial class CommentQuery
{
    public Guid Id { get; set; }

    public Guid PostId { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string CommentText { get; set; }

    public virtual PostQuery Post { get; set; }
}