// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ContentService.Infrastructure.Persistence.Sql.Queries.QueryModels;

public partial class PostQuery
{
    public Guid Id { get; set; }
    public List<Guid?> CategoryIds { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Text { get; set; }

    public virtual ICollection<CommentQuery> Comments { get; set; } = new List<CommentQuery>();
}